### ISSUE TITLE
{ } comments cause go to definition to go to wrong location

### ISSUE THREAD

**Issue by Synccept** [gregfullman/VSGenero#14]
If you use "Go To Definition" for a function which is in a file which uses {} type comments, the cursor will be put in the wrong location.  The cursor location will be offset by the number of lines in the block comment.

EG:

{this
is some 
comment }
function Foo()
end function

Going to the definition of Foo will place the cursor three lines lower than function Foo.

**Comment by gregfullman** [comment]
This bug is fixed and will be coming in the next release. Thanks for finding it!

**Comment by Synccept** [comment]
Pulled the code and it works great!  Thanks!

**Comment by gregfullman** [comment]
This bug fix is now available in version 0.9.7.5
