### ISSUE TITLE
Scheme causes "main block found in incorrect position"

### ISSUE THREAD

**Issue by Synccept** [gregfullman/VSGenero#15]
It appears the schema keyword is confusing the editor.  In the code below, function is underlined with "main block found in incorrect position" and the "go to definition" cannot find foo.

VS 2015 
VSGenero 0.9.7.6.  

```
schema test

define foo decimal(10,2)

main 
      call test()
end main

function test()
       let foo = 10
end function
```

Thank you for the excellent plug in.

**Comment by gregfullman** [comment]
This was fixed in commit e107b8e643c15daf684a0bc591039db10c55611f. Sorry for the delay!
