### ISSUE TITLE
Intellisense download and reload causes null exception

### ISSUE THREAD

**Issue by Synccept** [gregfullman/VSGenero#16]
**To repo:**

1.Open a 4gl file.
2.Go to Tools -> Options... > Text Editor -> Genero4GL -> Intellisense
3. "Click Download latest contexts"
4. "Click Reload completion contexts"
5. Click OK
6. Dialog closes and returns to the opened 4gl file focused.

**Result:**
After a short while an error dialog will repeatedly show with the details:

Exception Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: VSGenero2015
TargetMethod: [VSGenero2015]VSGenero.Options.Genero4GLIntellisenseOptionsControl::_timer_Tick()

StackTrace:
	   at VSGenero.Options.Genero4GLIntellisenseOptionsControl._timer_Tick(Object sender, EventArgs e)

InnerException: 
	System.NullReferenceException
	Object reference not set to an instance of an object.
	[VSGenero2015]VSGenero.Options.Genero4GLIntellisenseOptionsControl::_timer_Tick()

Other Info:

**Comment by gregfullman** [comment]
This was fixed in commit e107b8e643c15daf684a0bc591039db10c55611f. Sorry for the delay!
